version: '3.9'
services:
  app:
    container_name: fujila-next-server
    image: longthanhle1122/fujila-next:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000